-- MySQL Script generated by MySQL Workbench
-- mar. 30 mars 2021 15:25:31 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `movie_warehouse`.`writer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_warehouse`.`writer` (
  `id_writer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `birthDate` DATE NULL,
  `birthPlace` VARCHAR(45) NULL,
  PRIMARY KEY (`id_writer`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_warehouse`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_warehouse`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_warehouse`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_warehouse`.`country` (
  `id_country` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `alphacode` VARCHAR(45) NULL,
  `capital` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  PRIMARY KEY (`id_country`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_warehouse`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_warehouse`.`movie` (
  `id_movie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `release_date` DATE NULL,
  `duration` INT NULL,
  `number_of_seasons` INT NULL DEFAULT 0,
  `number_of_episodes` INT NULL DEFAULT 0,
  `filming_time` INT NULL DEFAULT 0,
  `main_actor` INT NULL,
  `id_writer` INT NOT NULL,
  `id_country` INT NOT NULL,
  `id_category` INT NOT NULL,
  `movie_source` ENUM('prime', 'netflix', 'disneyplus') NULL,
  `movie_type` ENUM('movie', 'tvshow') NULL,
  PRIMARY KEY (`id_movie`, `id_writer`, `id_country`, `id_category`),
  INDEX `fk_Movie_Writer1_idx` (`id_writer` ASC) VISIBLE,
  INDEX `fk_Movie_Country1_idx` (`id_country` ASC) VISIBLE,
  INDEX `fk_movie_category1_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_Movie_Writer1`
    FOREIGN KEY (`id_writer`)
    REFERENCES `movie_warehouse`.`writer` (`id_writer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_Country1`
    FOREIGN KEY (`id_country`)
    REFERENCES `movie_warehouse`.`country` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_category1`
    FOREIGN KEY (`id_category`)
    REFERENCES `movie_warehouse`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
